### ISSUE TITLE
RollingAppender does not work with HA node

### ISSUE THREAD

**Issue by No-PI** [ot4i/node-for-log4j#1] opened 2022-05-19 18:56 UTC
If you have an HA setup in IIB/ACE and use log4j to write to a common file (shared file system) from both systems, when the log rolls, one node will be pointed to the new file while the other retains the reference to the original file, causing log problems.

**Comment by rrehms** [comment] 2022-05-19 20:51
We are having the same issue where when the log rolls one side keeps appending to the file that has been renamed and not writing to the current file unless we stop the application and restart it.  So it seems it's not checking to see if it needs to reinitialize when the file name changes or something like that.

Was wondering if it maybe is fixed in the new version?

**Comment by nieder-github** [comment] 2022-05-20 06:29
I suppose the cause for this behaviour is in log4j itself. Seems that the RollingFileAppender does not support such a HA configuration. Please address this issue to log4j directly ( see: [https://issues.apache.org/jira/browse/LOG4J2-174](https://issues.apache.org/jira/browse/LOG4J2-174) ).
A workaround can be to use the FileAppender and implement the rolling outside e.g. by something like the following:
1) roll old log files ( use variables and a loop )
mv oldName.2 oldName.3
mv oldName.1 oldName.2
2) roll actual log file
cp -p oldName oldName.1
3) empty actual log file ( without renaming )
> oldName

**Comment by nieder-github** [comment] 2022-05-20 09:26
log4j issue

**Closed as completed** 2022-05-20 09:26 UTC
